#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum dhfsinam_fsichurn
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 213100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 213100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 213100002,
	}
}
#pragma warning restore CS1591
