#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum dhfsinam_fsilifestage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BuildingFuture = 213100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StartingaFamily = 213100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WealthAccumulation = 213100002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WealthDistribution = 213100003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WealthTransfer = 213100004,
	}
}
#pragma warning restore CS1591
