#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdh_fsiproductinterest
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BankAccount = 280410000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CreditCard = 280410001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Loans = 280410002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mortgages = 280410003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TermLoan = 280410010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryFinancing = 280410011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessInsurance = 280410014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssetFinancing = 280410012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinancialPlanning = 280410004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstatePlanning = 280410007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaxPlanning = 280410009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegisteredSavingsSolutions = 280410008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Advice = 280410005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HomeInsurance = 280410006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutoInsurance = 280410013,
	}
}
#pragma warning restore CS1591
