#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Dataverse.Model
{
	
	
	/// <summary>
	/// Type of Guides client used
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_clienttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HoloLens1 = 700610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HoloLens2 = 700610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Android = 700610002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		iOS = 700610003,
	}
}
#pragma warning restore CS1591
