#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Dataverse.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msfsi_profiletier
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 104800000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 104800001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 104800002,
	}
}
#pragma warning restore CS1591
